/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jbidwatcher_platform_Sparkle */

#ifndef _Included_com_jbidwatcher_platform_Sparkle
#define _Included_com_jbidwatcher_platform_Sparkle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jbidwatcher_platform_Sparkle
 * Method:    initSparkle
 * Signature: (Ljava/lang/String;ZI)V
 */
JNIEXPORT void JNICALL Java_com_jbidwatcher_platform_Sparkle_initSparkle
  (JNIEnv *, jclass, jstring, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
