#!/bin/bash

HERE=`dirname $0`
export JBIDWATCHER_LAUNCHER=true
while [ "$JBIDWATCHER_LAUNCHER" = "true" ]; do
  $HERE/JavaApplicationStub
  if [ "${?#0}" = "100" ]; then
    export JBIDWATCHER_LAUNCHER=true
  else
    export JBIDWATCHER_LAUNCHER=false
  fi
done
