CREATE TABLE my_jbidwatcher (
  id integer NOT NULL generated by default as identity (START WITH 1, INCREMENT BY 1),
  identifier varchar(255) default NULL,
  thumbnail_uploaded smallint default 0,
  last_synced_at timestamp default NULL,
  last_uploaded_html timestamp default NULL,
  snipe_submitted_at timestamp default NULL,
  currency varchar(10) default NULL,
  snipe_amount decimal(10,2) default NULL,
  PRIMARY KEY  (id)
)

CREATE INDEX IDX_MyJBidwatcher_Id ON my_jbidwatcher(identifier)
