CREATE TABLE devices (
  id integer NOT NULL generated by default as identity (START WITH 1, INCREMENT BY 1),
  device_id varchar(255) default NULL,
  security_key varchar(255) default NULL,
  PRIMARY KEY  (id)
)

CREATE INDEX IDX_Devices_Id ON devices(device_id)
